### ISSUE TITLE
Provide xunit test-reporter

### ISSUE THREAD

**Issue by mcbain** [practicalmeteor/spacejam#19]
Is it possible to generate a test-report xml parsable for teamcity or jenkins?

**Comment by meonkeys** [comment]
+1. Great idea!

**Comment by rbabayoff** [comment]
Hey, will one of you be willing to work on a pr for this? I can guide you through it.

**Comment by meonkeys** [comment]
@rbabayoff I think so! Will you describe what needs to be done? Specs can probably be entered right in this issue. I'm also in the meteor-talk google group and on the #meteor channel on Freenode (my nick is `meonkeys`) if you'd like to chat/discuss elsewhere.

**Comment by rbabayoff** [comment]
@meonkeys that's great. Let me go over code to see exactly what needs to be done.

**Comment by meonkeys** [comment]
Ping

**Comment by rbabayoff** [comment]
Hey, sorry, dropped the ball on this. I can get on a skype / google hangout to run you trough it. Just email me - rbabayoff@gmail.com.

**Comment by meonkeys** [comment]
See PR #28. I wish I could write to a file write from phantomjs `onConsoleMessage`, but I'm not sure how to do that.

**Comment by rbabayoff** [comment]
The best way would be to do it on the spacejam side, filter the phantomjs child process output and save to file there.

**Comment by meonkeys** [comment]
Ok, I'll take another look.

**Comment by meonkeys** [comment]
See PR #29.
