### ISSUE TITLE
bump phantomjs to 2.0 please

### ISSUE THREAD

**Issue by boxxxie** [practicalmeteor/spacejam#23]
latest stable version.

**Comment by rbabayoff** [comment]
I rather wait for 2.0.1 or 2.0.2.

**Comment by vsivsi** [comment]
:+1:  

Thanks for the great package, however  I need phantomjs 2.0 to test my [file-collection]() package that uses modern HTML5 file APIs. Pre-2.0 phantomJS uses a very old Webkit version: `Blob` and `FileReader` don't work at all in 1.9.x. https://github.com/ariya/phantomjs/issues/11013  
Would love to set-up travis on this package, but this issue prevents it from working.

**Comment by vsivsi** [comment]
@rbabayoff   It's been nearly 6 months, any progress on upgrading to phantomJS 2.0?

**Comment by savvopoulos** [comment]
+1

**Comment by savvopoulos** [comment]
FYI, the phantomjs package was stuck at 1.9 because the linux version was delayed (it seems like it was released recently).

In the meantime, you can do the following:
1) install phantomjs2 manually
 npm install -g phantomjs2
You may have to specify this flag, in case the package's link is broken:
--phantomjs_downloadurl=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2

2) run spacejam like this:
spacejam test-packages --use-system-phantomjs

**Comment by rbabayoff** [comment]
@savvopoulos yes, I'm waiting for it to be bumped and will also need to refactor my test runs, since phantomjs 2 doesn't support coffee. Thanks for documenting the workaround.

**Comment by savvopoulos** [comment]
Hi, according to https://www.npmjs.com/package/phantomjs
you will need to switch to https://www.npmjs.com/package/phantomjs-prebuilt
which is already in version 2.1.3.

Thanks for maintaining this package! Without it, my company wouldn't be using Meteor.

**Comment by savvopoulos** [comment]
Also, phantomjs is now in version 2.

**Comment by savvopoulos** [comment]
ping? Is there any chance to bump to a newer version of phantomjs? Would radically simplify my life .. :)

**Comment by cpury** [comment]
This is breaking our Circle CI setup, as spacejam insists on installing its own version of phantomjs, which ends up being rate-limited by bit bucket quite a lot.... We can work around it but it's annoying.
+1

**Comment by jsep** [comment]
Hello everyone, we just release a new version of spacejam that includes the latest version of spacejam, 
please install spacejam with `rc` tag or with version constraint.

```
npm -g install spacejam@rc
# or
npm -g install spacejam@1.6.0-rc.2

```

**Comment by vsivsi** [comment]
@jsep  I assume you mean "...includes the latest version of ***phantomjs***", and not spacejam, right?  😉

**Comment by jsep** [comment]
Hi @vsivsi it also have the latest version of spacejam with support for `meteor test` command.

**Comment by vsivsi** [comment]
Okay, good to know. Thanks!

**Comment by jsep** [comment]
Upgraded in 1.6.0
