### ISSUE TITLE
Function.prototype.bind is undefined in SpaceJam

### ISSUE THREAD

**Issue by johanbrook** [practicalmeteor/spacejam#24]
Great package! I use it for CI tests for my packages.

However, it said my test failed since my code under test was using `Function.prototype.bind`, which is `undefined` when running latest SpaceJam. I checked this by `console.log`-ing out `myFunction.bind` when running the test.

When using Underscore's `_.bind`, everything works smoothly.

**Comment by rbabayoff** [comment]
Hey, I suspect this is not a spacejam issue, it's a phantomjs issue that doesn't support Function.prototype.bind. I'd recommend therefore to stay with _.bind or use a bind shim until phantomjs supports it properly in a future version and spacejam upgrades to that version.

**Comment by johanbrook** [comment]
Okay, didn't know that! Thanks.
