### ISSUE TITLE
Error given at line of file that doesn't exist

### ISSUE THREAD

**Issue by micahblu** [practicalmeteor/spacejam#25]
I'm getting an error that's referencing a file which does not exist. Otherwise the error descriptors are very useful giving line and character info, but as it is, they serve no purpose since the file doesn't exist. I'm assuming the file is built at runtime, then removed in a clean up process. This makes debugging errors very difficult. Is there a way to circumvent this behavior for files containing errors? Thanks for building this btw, its a very useful tool :)

```shell
=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
I20150318-16:12:16.210(-7)? test-in-console listening
phantomjs: Running tests at http://localhost:4096/ using test-in-console
TypeError: 'undefined' is not an object (evaluating 'Dante')

  http://localhost:4096/packages/michelson_dante.js?ab34457c37a6f2a7bd2a91041d796514d6d58e43:2282
  http://localhost:4096/packages/michelson_dante.js?ab34457c37a6f2a7bd2a91041d796514d6d58e43:2284
  http://localhost:4096/packages/michelson_dante.js?ab34457c37a6f2a7bd2a91041d796514d6d58e43:4475
  http://localhost:4096/packages/michelson_dante.js?ab34457c37a6f2a7bd2a91041d796514d6d58e43:4484
TypeError: 'undefined' is not an object (evaluating 'Package['michelson:dante'].Dante')

  http://localhost:4096/packages/local-test_michelson_dante.js?a340085d8155b0fc004427a9dd673606cf246e0a:22
  http://localhost:4096/packages/local-test_michelson_dante.js?a340085d8155b0fc004427a9dd673606cf246e0a:54
passed/expected/failed/total 0 / 0 / 0 / 0
##_meteor_magic##state: done
spacejam: phantomjs exited with code: 0
spacejam: killing meteor
```

**Comment by rbabayoff** [comment]
Hey,

It doesn't look like it's a spacejam issue. The problem is in:

```
evaluating 'Package['michelson:dante'].Dante
```

If this is your code, I would:

```
if (Package['michelson:dante'] && Package['michelson:dante'].Dante)
```

It also may be a Dante export issue.

When running the tests in the browser, due you get the error?

**Comment by micahblu** [comment]
Yes I understand this not a spacejam error, most likely an error in the way I've setup the package, my question is: Is spacejam creating the file `http://localhost:4096/packages/michelson_dante.js` ?

**Comment by rbabayoff** [comment]
No, this is standard meteor. This is meteor's compile js or sourcemap file apparently.

**Comment by micahblu** [comment]
Thank you, that points me in the right direction :)
