### ISSUE TITLE
improve junit-output

### ISSUE THREAD

**Issue by mcbain** [practicalmeteor/spacejam#33]
Currently all spaces in test names get replaced by a dash. 
Since the output is utf-8 you could also use "another space char" e.g.  \u00A0

http://www.fileformat.info/info/unicode/char/00A0/index.htm.

Also in teamcity the testname is doubled, since the 'name' and 'classname' field contain the same values.

**Comment by rbabayoff** [comment]
I don't control xunit output, meteor does. Please file it there. meteor's code is here:

https://github.com/meteor/meteor/blob/devel/packages/test-in-console/driver.js

**Comment by rbabayoff** [comment]
I only make meteor generate it and save it to file. But you can always take the output file and process it to your needs.

**Comment by mcbain** [comment]
Thanks, for the hint to driver.js
