### ISSUE TITLE
Test cannot run on client (error preventing script execution) but build is ok

### ISSUE THREAD

**Issue by p-j** [practicalmeteor/spacejam#40]
Hi,

It seems that if the client side tests are not run because of a javascript error prior to the execution, the build will end successfully no matter what. 

Here is an [example](https://travis-ci.org/p-j/meteor-gravatar/builds/76004361#L181)
The `Npm` variable is not set because it is not expected to run on the client side, only the server side, this will prevent the client side test from ever being run... But the build will be marked as successful because the test server are successful.

Is their a way to get the correct behavior ? (ie: if it crash, then its not ok)

Thanks for your work on this package, it is really helpfull !

**Comment by jsep** [comment]
Hi @p-j thank for the issue I'll have a look later. If you like mocha you should try our [mocha](https://atmospherejs.com/practicalmeteor/mocha) package zero dependencies with velocity and works perfectly with `spacejam`.

To run your tests with mocha and spacejam:
1) Add `practicalmeteor:mocha` package instance of `tinytest`
2) run `spacejam test-packages --driver-package=practicalmeteor:mocha-console-reporter`

**Comment by billyvg** [comment]
We're having the same issue:

```
SyntaxError: Parse error

ReferenceError: Can't find variable: ReactiveVar

  http://localhost:4096/packages/opstarts-calcengine.js?989f0cb4541ce165901a708e8d5d9c15522ead79:15181
  http://localhost:4096/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:785
  http://localhost:4096/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:787
passed/expected/failed/total 0 / 0 / 0 / 0
```

Then it ran tests for other packages.

**Comment by jsep** [comment]
`spacejam`  will exit with non success status if:
*  spacejam internal error.
* At least one test has failed.
*  The meteor app exited with an error or is crashing.
*  The tests have timed out

Basically if `meteor` compiles and runs `spacejam` will look for at least a failing test.

**Comment by p-j** [comment]
Shouldn't it look for Phantoms output as well?

**Comment by jsep** [comment]
Yes, we are looking for phantomjs ouput but its hard to know whether the client tests are broken or its just an simple exception of tests.

**Comment by billyvg** [comment]
Shouldn't spacejam also exit with non success status if phantomjs throws an error?
