### ISSUE TITLE
--xunit-out creates empty output file

### ISSUE THREAD

**Issue by jeffryan** [practicalmeteor/spacejam#48]
Performing the following command:
$ spacejam-mocha --xunit-out results.xml

This runs all testcases for all project packages and reports the results to the console normally. However, although the results.xml file does get created, its contents are empty. I've tried conditions where all test cases pass and where some fail but the result is the same.

Am I invoking the option correctly? 

I'm using version 1.5.1 of spacejam against meteor 1.2.1

**Comment by jeffryan** [comment]
I should mention that I was originally trying to run the tests like this:

$ spacejam --xunit-out results.xml  test-packages --driver-package=practicalmeteor:mocha-console-runner

and then later moved to the spacejam-mocha syntax in my first post. I seem to get the same result either way.

**Comment by rbabayoff** [comment]
@jeffryan, I won't have time to take a look at this this week. I'll take a look at it next week. In the meantime, see if an older version of spacejam works or you:

```
npm install -g spacejam@1.3.0
```

**Comment by jeffryan** [comment]
no worries... i'm out till late next week anyway. I did give 1.3.0 and am having the same issue. One thing I notice looking at the code and the console output is that I never see the  '_meteor_magic_' message come through on the console. However, I do see that message when running spacejam through starrynight. so I'm not sure how thats happening. I need to dig into the starrynight code to see how it's invoking you but seemed like running spacejam straight from the console should be the simplest scenario.

**Comment by jeffryan** [comment]
Hi Ronan, I'm back looking at this again. Thought I would give a little more information about what I'm seeing when I run the test. I ran the tests again but this time with --loglevel trace and I've included the output in the attached file. Looking through the output I don't see any errors. It looks like Phantomjs is getting invoked with related options as shown below but again the result file is empty.

_Phantomjs.run() { '0': 'http://localhost:4096/xunit',
  '1': '--load-images=no --ssl-protocol=TLSv1',
  '2': 'phantomjs-test-in-console',
  '3': { [Function: XunitFilePipe] __super__: {} },
  '4': { pipeToFile: 'tests/spacejam/reports/results.xml' },
  '5': false }
_

If you can think of anything else I might try to help debug let me know. Thanks.

Jeff
[debuglog.txt](https://github.com/practicalmeteor/spacejam/files/112634/debuglog.txt)

**Comment by rbabayoff** [comment]
@jeffryan I apologize, there has been a confusion on our side - xunit output is only supported for meteor tinytests, not for mocha. But, the good news is that we're working on supporting xunit output for mocha tests too. We'll have a release candidate out there for you to check today or tomorrow.

**Comment by jeffryan** [comment]
That would be great Ronan. Will this work with meteor 1.3? We've moved our project over but we have not gotten our tests running through spacejam since the move.

**Comment by jsep** [comment]
Hello @jeffryan we just release `practicalmeteor:mocha-xunit-reporter` and its working with Meteor 1.3, here how to use it.

1) Install 1.6.0-rc1 of spacejam. Run this: `npm install -g spacejam@1.6.0-rc`
 2) `meteor add practicalmeteor:mocha-xunit-reporter`
3) To run tests: `spacejam test --driver-package practicalmeteor:mocha-xunit-reporter --full-app  --xunit-out results.xml`

**Comment by jeffryan** [comment]
Thanks @jsep 
Currently our mocha tests are package tests... can I expect those to work as well?

**Comment by jeffryan** [comment]
I'll give this a shot sometime today and report back. Thanks alot.

**Comment by jsep** [comment]
Yes it's the same for tests, only use `spacejam test-packages --driver-package practicalmeteor:mocha-xunit-reporter --full-app --xunit-out results.xml`.

**Comment by jeffryan** [comment]
@jsep I am trying to install the new release candidate version but npm can't seem to find it:

$ npm install -g spacejam@1.6.0-rc
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "spacejam@1.6.0-rc"
npm ERR! node v0.10.43
npm ERR! npm  v2.15.0
npm ERR! version not found: spacejam@1.6.0-rc
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:

I am using the default npm registry: https://registry.npmjs.org/

Do I need to point to a different registry or does it just take time for the package to propogate?

**Comment by jsep** [comment]
Sorry my bad @jeffryan is `1.6.0-rc1`

`npm install -g spacejam@1.6.0-rc1`

**Comment by jeffryan** [comment]
@jsep I've tried this with a couple packages now and I'm seeing a few issues:
1. Each test seems to be ran twice. Ex:
```
C: Welcome (Wizard) tests should render welcome components : passed

C: Welcome (Wizard) tests should render welcome components : passed

```
2. The program doesn't seem to return once all the tests are complete. Just hangs indefinitely.
3. When I finally terminate the program with ctl-C I look at the xunit result file and it is created but empty

Here's a little more info:

- We're on meteor 1.3.0 currently.
- We run our tests interactively like this:</br>
`$ meteor test-packages --driver-package=practicalmeteor:mocha`</br>
they seem to run normally (ie just result per test case)
- I am invoking spacejam like this:</br>
`$ spacejam test-packages --driver-package=practicalmeteor:mocha-xunit-reporter --full-app --xunit-out results.xml`</br>

I've tried with and without --full-app with same results. Anything more I can try to help debug?

**Comment by jsep** [comment]
I think it's enough to debug, what about the results.xml it's working?

**Comment by jeffryan** [comment]
no its empty... however, I am killing the program after some idle minutes so maybe it's stuck somehow trying to write or close that file.

**Comment by jsep** [comment]
ok, thanks @jeffryan

**Comment by jeffryan** [comment]
no problem... let me know if you want me to give it another go.

**Comment by rbabayoff** [comment]
@jeffryan, when using test-packages, don't use --full-app, --full-app is only for running meteor app tests, when using the new `meteor test` command in meteor 1.3. See the [meteor guide](http://guide.meteor.com/testing.html) for additional info.

**Comment by jeffryan** [comment]
OK - thanks for clarifying @rbabayoff.  unfortunately as mentioned above I tried both with and without the --full-app with same results.

**Comment by rbabayoff** [comment]
Also, I'd recommend always installing the version of meteor you need before running spacejam in ci envs, by running:

```
meteor --release 1.3 --version
```

**Comment by jeffryan** [comment]
yep - thats what we've done. thanks.

**Comment by rbabayoff** [comment]
@jeffryan:

1. What OS are you on? 
2. What node version are you using?
3. Can you create a repo that reproduces this for us?

**Comment by jeffryan** [comment]
Hi @rbabayoff 
I'm running on osx v10.11.4 (El Cap)
Node v0.10.43 (same as meteor)
Meteor v1.3.0

I can make you a repo but it may take me a week or so... we are in the midst of wrapping up a new product and its our final crunch right now. Definitely want to get this working though as we begin ramping up development on this product line. Just give me a few days ;)

Thanks

**Comment by jsep** [comment]
Hello @jeffryan I've just release a new version of the package that should solve the issues, please try again and let me now.

The new version of `practicalmeteor:mocha-xunit-reporter` is  ` 0.1.0-rc.2`

**Comment by jeffryan** [comment]
Thanks @jsep I'll give it a try. By the way,  I can't help but notice the version # your suggesting has changed as well as the rc #... so I should be doing:
$ npm install -g spacejam@0.1.0-rc.2   ?

previous version was:
$ npm install -g spacejam@1.6.0-rc.1

**Comment by jsep** [comment]
@jeffryan you don't have to change the version of spacejam, you can still use `spacejam@1.6.0-rc1`

**Comment by jeffryan** [comment]
oh got it - was thinking the reporter was part of the spacejam package... trying it now thanks.

**Comment by jeffryan** [comment]
Hi @jsep here's what I've found.
First I just tried adding 
`    api.use('practicalmeteor:mocha-xunit-reporter@0.1.0-rc.2');`
to my Package.onTest section of the package we were testing. But this was not adequate to allow for me to run spacejam with the mocha-xunit-reporter driver. So then I tried adding that package directly to the main meteor application as follows:
`$ meteor add practicalmeteor:mocha-xunit-reporter@0.1.0-rc.2`

This worked... now I can run the package tests using spacejam and the output goes to the console. Here's a snippet of the run:

```
$ spacejam test-packages --driver-package=practicalmeteor:mocha-xunit-reporter --xunit-out results.xml
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/xunit using test-in-console
Warning: [react-router] Location "" did not match any routes
Warning: [react-router] Location "" did not match any routes
C: Alerts should use default options when none provided : passed

C: Alerts should override default options with options argument : passed

C: Alerts should handle undefined message and title : passed

C: Alerts should allow clearing alerts : passed

....etc...
```

couple issues remain however:
1. results.xml is still empty - perhaps this fix did not address that.
2. spacejam does not exit after the tests complete... that is it is still running and I have to manually kill it. Ideally it exists with a return code indicating if tests passed or failed.

Progress none the less! Thanks for you hard work!

Jeff

**Comment by denodaeus** [comment]
Also having the same issue Jeff has posted above, mainly:

1) results.xml is empty
2) space jam doesn't exit after the tests are complete

Also, we're having an issue where meteor seems to hang at 100% CPU utilization (the process spawned by space jam), about 30% of the time, but we'll follow up on a different issue after trying to track down what's going on.

Thanks,

**Comment by jsep** [comment]
Hi @jeffryan, @denodaeus, I can't reproduce the problem a demo repo will be very helpful.

By the way did you guys try to run the tests using just `meteor test` command? maybe we can find the problem using meteor and not spacejam.

Please try this:

For app
```
meteor add practicalmeteor:mocha-xunit-reporter@0.1.0-rc.2
meteor test --driver-package practicalmeteor:mocha-xunit-reporter
```
For packages under Package.onTest
```
api.use('practicalmeteor:mocha-xunit-reporter@0.1.0-rc.2');
```

```
To run tests:
meteor test-packages --driver-package practicalmeteor:mocha-xunit-reporter
```


Go to `http://localhost:3000` open the console and you should see the tests in the console. At the end you should see the xunit test suite.

I'm also available to hangout in order  solve this issue. 

Thanks,

**Comment by minid33** [comment]
@jsep I did try your troubleshooting and got no results as well when using `mocha-xunit-reporter`, I also get it when using `spacejam-mocha`

**Comment by mcbain** [comment]
I have the same problem, output file is always empty

**Comment by thebarty** [comment]
Hi guys,

it's been a while: I just stumbled upon the same problem - being UNABLE to get a xml output. I have tried on both local OSX and CircleCi.

**Did you guys make any progress? Can you share which solution you are using right now?**
