### ISSUE TITLE
tests fail in spacejam but on under meteor test-packages

### ISSUE THREAD

**Issue by savvopoulos** [practicalmeteor/spacejam#49]
My test fails on this line:
  scheduler.update().should.include.something.that.eql({

With:
TypeError: Cannot read property 'that' of undefined

'something.that' is chai-things syntax. It's a handy library for checking results. It seems to have a weird way of initializing the module, could that be it?
From: https://github.com/chaijs/chai-things/blob/master/lib/chai-things.js

  // NodeJS
  if (typeof require === "function" && typeof exports === "object" && typeof module === "object")
    module.exports = chaiModule;
  // AMD
  else if (typeof define === "function" && define.amd)
    define(function () { return chaiModule; });
  // Other
  else
    chai.use(chaiModule);

**Comment by savvopoulos** [comment]
I created a special version that removes the suspicious code, and added it as a dep to my project, but it didn't fix the problem.

It must be something else.

**Comment by rbabayoff** [comment]
The error message says that `something` is undefined, which means that `should.include` is defined. If it works with meteor test-packages, it's probably an incompatibility problem with phantomjs, which spacejam uses for browser testing. Can you try and install the latest version of phantomjs and then run spacejam with `--use-system-phantomjs=true`?

**Comment by savvopoulos** [comment]
Thanks for the response! I fixed that issue by using another library.

However, it seems that phantomjs 1.9 is really out of date: I got the issue again, a day later, with the react library... --use-system-phantomjs fixes the issue. Thanks for that.

Now I will need to figure out a way to convert that into a circle.yml file .. :) and hopefully that's the last I will have to do my meteor CI!

**Comment by savvopoulos** [comment]
This is how I got it to work with CircleCI:


dependencies:
  cache_directories:
    - ~/.meteor
  override:
    - meteor || curl https://install.meteor.com | /bin/sh
    - npm install -g phantomjs2  --phantomjs_downloadurl=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - npm install -g spacejam

test:
  override:
    - spacejam test-packages --use-system-phantomjs

**Comment by rbabayoff** [comment]
@savvopoulos great! I'll add it to the readme.

**Comment by savvopoulos** [comment]
Hi Ronen

At this point, a better solution might be to upgrade to the latest version of phantomjs, which is easy since there are a few npm packages out there -- see my other comment.

**Comment by rbabayoff** [comment]
@savvopoulos I know, problem is that phantomjs 2.0 doesn't support coffee and our spacejam unit tests run in coffee. Need to refactor stuff a bit to make this work with 2.0. Will get to it soon.

**Comment by savvopoulos** [comment]
thank you :)
