### ISSUE TITLE
Issue with wrong version of package... Can I enforce a certain version?

### ISSUE THREAD

**Issue by cpury** [practicalmeteor/spacejam#54]
Our app works perfectly, and even running spacejam locally doesn't pose a problem.
However, since yesterday, all our automated tests on Circle CI fail:

```
/home/ubuntu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
 						throw(ex);
 						      ^
 Error: HTTP.methods not implemented on client-side
     at Object.HTTP.methods (packages/cfs_http-methods/http.methods.client.api.js:5:1)
     at [object Object]._.extend._registerHTTPMethod (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:82:10)
     at packages/tap_i18n/lib/tap_i18n/tap_i18n-common.coffee:39:10
     at /tmp/meteor-test-run1jsjo92/.meteor/local/build/programs/server/boot.js:249:5
```

Turns out a lot of people were getting this problem at the same time: https://github.com/TAPevents/tap-i18n/issues/160 . Not sure how, since neither `tap:i18n` nor `cfs:http-methods` had a recent update, and we're fixing the version of `tap:i18n` to `@1.8.0` throughout our code, and `tap:i18n` is using `cfs:http-methods@0.0.27`. Our own app's `versions` file has the version set to `cfs:http-methods@0.0.30`.

So, spacejam is creating a test app for all the packages, right? If so, where can I find its `versions` file? And how could I enforce a specific version?

Thanks a lot for any help. This is blocking us since all our automated tests are failing...

**Comment by jsep** [comment]
@cpury 

You can try adding the package with a  version constrain `meteor add  cfs:http-methods@0.0.30`.

Spacejam basically run `meteor test-packages` and the app meteor creates is under `/tmp/meteor-test-run<random-id>`

**Comment by cpury** [comment]
@jsep thanks for the info! That way I at least can investigate which versions the spacejam app uses.

We're not using `cfs:http-methods` directly, but at least two packages we use seem to use it. I guess some package somewhere has `cfs:http-methods` as an requirement without fixing the version which causes the newest version to be used.

**Comment by rbabayoff** [comment]
Closing this, since it's not a spacejam issue.
