### ISSUE TITLE
1.6.0 fails with coffee: No such file or directory

### ISSUE THREAD

**Issue by dburles** [practicalmeteor/spacejam#55]
We recently noticed our builds were failing on circleci along with this error:
```
spacejam test-packages
/usr/bin/env: coffee: No such file or directory

spacejam test-packages returned exit code 127
```
on taking a look into it I realised they were installing 1.6.0 previously 1.5.2.

Any idea what's causing this issue on the latest version?

**Comment by jsep** [comment]
@dburles Yes it;s going to be release in next version today.

For now please add this:
```
npm install -g coffee-script@1.8.0

```

**Comment by dburles** [comment]
thanks @jsep !

**Comment by dburles** [comment]
Hey still seeing this problem with 1.5.2
