### ISSUE TITLE
env: coffee: No such file or directory

### ISSUE THREAD

**Issue by keyscores** [practicalmeteor/spacejam#56]
Getting this error on installing and running spacejam.
Meteor. 1.3.2-rc.5  , Mac OSX

>npm install -g spacejam
// ok
>spacejam test --driver-package practicalmeteor:mocha
// env: coffee: No such file or directory

**Comment by jsep** [comment]
@keyscores You can solve this by running:

```
npm install -g coffee-script@1.8.0
```

This it's going to be fix in the next release

**Comment by jsep** [comment]
This should be fixed
