### ISSUE TITLE
Error: Cannot find module '../lib/log' #57

### ISSUE THREAD

**Issue by serut** [practicalmeteor/spacejam#60]
travis can't run `bin/spacejam`, it throws this error: `Error: Cannot find module '../lib/log'`

Here is the list of operation that I did on travis

```
    npm install -g https://github.com/practicalmeteor/spacejam/tarball/master coveralls
    spacejam test            --loglevel debug --driver-package=practicalmeteor:mocha-console-runner --coverage
    module.js:340
    throw err;
    ^
    Error: Cannot find module '../lib/log'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/spacejam/bin/spacejam:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    The command "spacejam test --loglevel debug --driver-package=practicalmeteor:mocha-console-runner --coverage" exited with 8.
```

You can find the entire log here: https://travis-ci.org/serut/meteor-coverage-app-exemple/builds/134144135

Node try to require the file `../lib/log.js` and not the file `../lib/log.coffee`. This is exactly this use case: https://stackoverflow.com/questions/4768748/requireing-a-coffeescript-file-from-a-javascript-file-or-repl
Please integrate my pull request https://github.com/practicalmeteor/spacejam/pull/57 that fix this issue.

**Comment by maxnowack** [comment]
Same issue on circleci ...

**Comment by serut** [comment]
Can you try with the last version `1.6.2-rc.4` of spacejam ?

**Comment by maxnowack** [comment]
Yes, it's working with the lastest rc.
Thank you! :)

**Comment by vsivsi** [comment]
@serut  Can you make `spacejam@1.6.2-rc.4` the default install on npm?  Right now if you just say:

```
npm install -g spacejam
```

You still get `spacejam@1.6.2-rc.2`, with this issue.  I'd really prefer not to hard-code versions (esp. release candidates) into to my TravisCI.

On second thought, perhaps the npm default install should remain `1.6.1` until the final release of 1.6.2 is ready?

**Comment by vsivsi** [comment]
Specifically:

```
% npm dist-tag ls spacejam
1.1.0-rc1: 1.1.0-rc1
1.1.0-rc2: 1.1.0-rc2
1.1.0-rc3: 1.1.0-rc3
devel: 1.1.0-rc15
latest: 1.6.2-rc.2
rc: 1.6.2-rc.4
```

Tag `latest` should be set to either version `1.6.2-rc.4` (the real latest) or `1.6.1` the latest solid release. 

Thanks!

**Comment by jsep** [comment]
I was my bad, the latest now it's `1.6.1`
