### ISSUE TITLE
`latest` tag on npm points to broken version `1.6.2-rc.2`

### ISSUE THREAD

**Issue by vsivsi** [practicalmeteor/spacejam#64]
See comments here for context: https://github.com/practicalmeteor/spacejam/issues/60#issuecomment-231860659

Running this *should* fix it:

```
npm dist-tag add spacejam@1.6.1 latest
```

**Comment by jsep** [comment]
Thanks, it's fixed now

**Comment by vsivsi** [comment]
Thanks for the quick fix!
